### PR TITLE
fix: security + correctness bugs (#123-#128)

### LINKED ISSUE #123: bug: CSS injection in spacer height, image grid gap, sidebar width, and divider properties
## Bug
Several component properties from page spec JSON are interpolated directly into inline `style` attributes without sanitization:

1. **Spacer** — `@height` in `style={"height: #\{@height}"}`
2. **Image grid** — `@gap` in `style={"gap: #\{@gap}"}`
3. **Sidebar** — `@sidebar.width` in `style={"width: #\{@sidebar.width}"}`
4. **Divider** — `thickness`, `color`, `max_width` all unsanitized

An attacker (or malformed page spec) could inject arbitrary CSS or break the page.

## Fix
Validate these values (e.g. must match `/^\d+(\.\d+)?(px|rem|em|%|vw|vh)$/`) before rendering.
Add a `sanitize_css_value/1` helper to StyleValidator that strips dangerous patterns.

### PR DESCRIPTION
**Pull request by quigles1977**
Closes #123 #124 #125 #126 #127 #128

## Security Fixes
- `sanitize_css_dimension/1` — validates spacer height, image grid gap, sidebar width, divider thickness/max_width against regex `/^\d+(\.\d+)?(px|rem|em|%|vw|vh|...)$/`
- Viewport `responsive_class` only accepts integer `min_width`/`max_width` (prevents CSS class injection)

## Crash Fix
- `hydrate_all` handles `Task.async_stream` `:exit/:timeout` gracefully — falls back to original component instead of crashing

## Data Fix
- Hydrated products now include `variant`, `badge`, `compare_at_price`, `description` fields (parity with inline products from #100)

## Money Fix
- `compute_subtotal` uses integer cents arithmetic to avoid floating point rounding errors (e.g. `£269.70` instead of `£269.70000000000002`)

## Test Fix
- Analytics uses `Logger.warning` (not `Logger.info`), removing global `Logger.configure` race condition that caused flaky tests

4 new tests, 448 total. Precommit: 448/20

### CODE REVIEW

File: lib/jarga_admin_web/components/storefront_components.ex [hunk 1]
```diff
@@ -941,13 +941,16 @@ defmodule JargaAdminWeb.StorefrontComponents do
 
   def divider(assigns) do
     color_style = if assigns.color, do: "border-color: #{sanitize_hex(assigns.color)};", else: ""
-    width_style = if assigns.max_width, do: "max-width: #{assigns.max_width};", else: ""
+    safe_width = StyleValidator.sanitize_css_dimension(assigns.max_width)
```
Comment (quigles1977) [inline lib/jarga_admin_web/components/storefront_components.ex]: [info] **Good fix** — divider `max_width` and `thickness` now sanitized through `sanitize_css_dimension`. Falls back to `1px` for thickness and omits `max-width` entirely if invalid.

File: lib/jarga_admin_web/live/storefront_live.ex [hunk 2]
```diff
@@ -476,7 +482,7 @@ defmodule JargaAdminWeb.StorefrontLive do
               @sidebar.position == "right" && "sf-sidebar-right",
               @sidebar.sticky && "sf-sidebar-sticky"
             ]}
-            style={"width: #{@sidebar.width}"}
+            style={"width: #{JargaAdmin.StyleValidator.sanitize_css_dimension(@sidebar.width)}"}
```
Comment (quigles1977) [inline lib/jarga_admin_web/live/storefront_live.ex]: [info] **Good fix** — sidebar width now sanitized through `StyleValidator.sanitize_css_dimension(@sidebar.width)`.

File: lib/jarga_admin/storefront_hydrator.ex [hunk 3]
```diff
@@ -151,7 +151,18 @@ defmodule JargaAdmin.StorefrontHydrator do
...
       )
-      |> Enum.map(fn {:ok, result} -> result end)
+      |> Enum.zip(to_hydrate)
+      |> Enum.map(fn
+        {{:ok, result}, _original} ->
+          result
+
+        {{:exit, reason}, {comp, idx}} ->
+          Logger.warning(
+            "StorefrontHydrator: task failed for component #{idx}: #{inspect(reason)}"
```
Comment (quigles1977) [inline lib/jarga_admin/storefront_hydrator.ex]: [low] **Crash payload in logs** — `inspect(reason)` on a timed-out/crashed task may include internal state, stack traces, or partial data from the API response. Consider logging only the exit type (`:timeout`, `:killed`, etc.) rather than the full reason to avoid potential data leakage in log aggregators.
